name: Ryoji's GitHub Actions Demo - Github Actions -> Build -> Scan -> ECR 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs: 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get short SHA
        run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV 

      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: ryo-ecr/ryo-test-1:${{ env.GHA_SHA }},ryo-ecr/ryo-test-1:latest
          load: true

      - name: Scan container images for vulnerabitilies using Lacework
        uses: lacework/lw-scanner-action@v0.6.0
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ryo-ecr/ryo-test-1
          IMAGE_TAG: latest
          BUILD_REPORT_FILE_NAME: myreport.html
          SAVE_RESULTS_IN_LACEWORK: true
          SCAN_LIBRARY_PACKAGES: true
          FAIL_BUILD: true
          SEVERITY_THRESHOLD: high
          USE_POLICY: true

      - name: Login to ECR
        id: ecr
        uses: elgohr/ecr-login-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ryo-ecr
          username: ${{ steps.ecr.outputs.username }}
          password: ${{ steps.ecr.outputs.password }}
          registry: ${{ steps.ecr.outputs.registry }}